# Generated by Django 5.1.3 on 2024-12-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Title',
        ),
    ]
